### PR TITLE
Remove inline javascript from Option Builder tools to fix issue #306

### PR DESCRIPTION
**Pull request by paulcheeseman**
- Moved all javascript into separate .js files
- Removed all inline event handlers from the HTML and added equivalent addEventListener() calls

Signed-off-by: Paul Cheeseman <paul.cheeseman@uk.ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
Jenkins website stage

**Comment by pshipton** [comment]
@AdamBrousseau @doveye there is an error trying to stage, but it doesn't seem to be related to this change.
In the console output I see some warnings followed by a `Error: EACCES: permission denied` error.

**Comment by AdamBrousseau** [comment]
Jenkins website stage

**Comment by doveye** [comment]
The build last worked on Dec 7. The next build, on Mar 29, failed. There were no changes in the repo between these two dates except to latestRelease.md, which can't have caused this error. The difference in the logs seems to start just after the line `Setting up nodejs (10.24.1-1nodesource1)`. The command in the Dockerfile that failed is `/bin/sh -c curl -sL https://deb.nodesource.com/setup_10.x | bash - && apt-get install -y nodejs && npm install -g gatsby-cli`.
The failing log contains `[91mgyp[0m[91m WARN[0m[91m EACCES[0m[91m current user ("nobody") does not have permission to access the dev dir "/root/.cache/node-gyp/10.24.1"`.

Definitely some sort of permissions error. Could something have changed in the underlying build system to cause this?

**Comment by doveye** [comment]
Jenkins website stage

**Comment by AdamBrousseau** [comment]
Jenkins website stage

**Comment by pshipton** [comment]
https://staging.eclipse.org/openj9/tools/xdump_option_builder.html
https://staging.eclipse.org/openj9/tools/xtrace_option_builder.html

lgtm

**Review by pshipton — APPROVED** [review]

**Pull request merged**
