### PR TITLE
What's New update for 0.27

### PR DESCRIPTION
**Pull request by doveye**
Closes https://github.com/eclipse-openj9/openj9-website/issues/294

Signed-off-by: Esther Dovey <doveye@uk.ibm.com>

### CODE REVIEW

**Comment by doveye** [comment]
Jenkins website stage

**Comment by AdamBrousseau** [comment]
Jenkins website stage

**Comment by doveye** [comment]
Jenkins website stage

**Comment by doveye** [comment]
Jenkins website stage

**Comment by doveye** [comment]
Jenkins website stage

**Comment by doveye** [comment]
@pshipton Hi Peter. Could you please merge this PR - the issues seem to have resolved themselves and the changes are now visible on the staging site at https://staging.eclipse.org/openj9/news/.

**Comment by mstoodle** [comment]
lgtm, i'll merge.

**Pull request merged**
