### PR TITLE
Remove obsolete 0.27 release notes

### PR DESCRIPTION
**Pull request by pshipton**
The "New Release Info" button that remains is sufficient.

Signed-off-by: Peter Shipton <Peter_Shipton@ca.ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
Jenkins website stage

**Comment by pshipton** [comment]
Staged to https://staging.eclipse.org/openj9/news
Ask we if you need the password. It's not perfect, but better than having obsolete info.

**Comment by keithc-ca** [comment]
Would it not make more sense to update to the release notes for 0.29?

**Comment by pshipton** [comment]
I expect so, I could work on that later.

**Review by keithc-ca — APPROVED** [review]

**Pull request merged**
